# Generated by Django 5.2.5 on 2025-08-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
            ],
        ),
    ]
